import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HypeReality",
  description: "Generated by create next app",
};

export default async function RootLayout({  
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " bg-gradient-to-b from-slate-200 to-100% to-gray-200 overflow-x-hidden"
        }
      >
        <div className="h-[2000px]">
          <Navbar />
          {children}

          <div className=" relative bottom-0 text-center text-comms">
            <h3>
              Made by <span className="text-firstPart">Szücs</span> Levente
            </h3>
          </div>
        </div>
        
      </body>
    </html>
  );
}
