
import "./globals.css";
import type { Metadata } from "next";
import { useLayout } from "@/utils/useLayout";
import { Suspense } from "react";
import { IronSessionData } from "iron-session";
import Loading from "@/components/Lodaing";

import NormalNavbar from "@/components/Navbars/NormalNavbar";
import { useSession } from "@/utils/session";
import { SessionProvider } from "next-auth/react";
import Providers from "./Providers";
export const metadata: Metadata = {
  title: "HypeReality",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body
        className={
          " bg-gradient-to-b h-screen from-slate-200 to-100% to-gray-200 overflow-x-hidden "
        }
      >
          <Providers>
            {children}
          </Providers>        
      </body>
    </html>
  );
}
export const revalidate = 3600;
